services:
  modules-app:
    build: .
    container_name: modules-app
    restart: always
    ports:
      - "3002:3000"
    volumes:
      - .:/app
    command: ["bun", "run", "app.js"]
    environment:
      - NODE_ENV=production