services:
  modules-app:
    image: "git.pontusmail.org/aidan/modules:latest"
    container_name: modules-app
    restart: always
    ports:
      - "3002:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production